---

- hosts: all
  become: true
  pre_tasks: 

  # This avoids the need of udpating the cache before every other task
  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    changed_when: false # does NOT consider this a change, for a cleaner output
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu) # in case I end up using Ubuntu servers
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles: 
    - common