- hosts: all
  become: true
  vars:
    target_zone: "target_zone"
  handlers:
    # A need stated in the firewalld documentation
    - name: reload_firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
  tasks: