---

# Ansible documentation:
# "This also means that you will have to reload firewalld 
# after adding a zone that you wish to perform immediate actions on"
- name: reload_firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded