---
# Configure firewalld 

# FIRST, run this FROM THE HOST COMPUTER to ensure propper use:
# `ansible-galaxy collection install ansible.posix`

- name: ensure its installation (firewalld)
  tags: 
    - start
    - firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: ensure it's running and enabled (firewalld)
  tags: 
    - start
    - firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: ensure the presence of the target zone (firewalld)
  tags: 
    - start
    - firewalld
  ansible.posix.firewalld:
    zone: "{{ common_target_zone }}"
    state: present
    permanent: true
  notify: reload_firewalld

# FROM HERE, it's the configuration itself
- name: change the zone of the ssh service
  tags: 
    - firewalld
  ansible.posix.firewalld:
    zone: "{{ common_target_zone }}"
    service: ssh
    state: enabled
    permanent: true

#! Works flawlessly for interfaces NOT already attached to a zone
- name: change the zone of the target interface 
  tags: 
    - firewalld
  ansible.posix.firewalld:
    zone: "{{ common_target_zone }}" 
    interface: eth0
    state: enabled
    permanent: true
  notify: reload_firewalld

# Zones are specially useful if the server changes its location 
# (if it runs in a RaspBerryPi, ...)   