---
# Install basic packages

- name: install basic packages (CentOS) # my common general needs
  tags: start
  ansible.builtin.package:
    name:
      - bash-completion
      - bind-utils
      - curl
      - epel-release
      - firewalld
      - gcc
      - git
      - lsof
      - nano
      - net-tools
      - nmap
      - python3
      - rsync
      - sysstat
      - tar
      - tcpdump
      - telnet
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - yum-utils
    state: latest
    update_cache: yes
